/*****************************************************************************
* Copyright (c) [2019] - [2026], Argenox Technologies LLC
* All rights reserved.
* SPDX-License-Identifier: GPL-2.0-or-later OR NoxTLS-Commercial
*
* File:    noxtls_check_config.h
* Summary: Compile-time configuration dependency checks
*/

#ifndef _NOXTLS_CHECK_CONFIG_H_
#define _NOXTLS_CHECK_CONFIG_H_

/* Boolean sanity checks for 0/1 style feature toggles. */
#define NOXTLS_CFG_BOOL_OK(v) ((v) == 0 || (v) == 1)

#if !NOXTLS_CFG_BOOL_OK(NOXTLS_CT_COMPARE)
#error "NOXTLS_CT_COMPARE must be 0 or 1."
#endif

#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_HASH)
#error "NOXTLS_FEATURE_HASH must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_ENCRYPTION)
#error "NOXTLS_FEATURE_ENCRYPTION must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_DRBG)
#error "NOXTLS_FEATURE_DRBG must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_PKC)
#error "NOXTLS_FEATURE_PKC must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_CERT)
#error "NOXTLS_FEATURE_CERT must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_TLS)
#error "NOXTLS_FEATURE_TLS must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_TLS10)
#error "NOXTLS_FEATURE_TLS10 must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_TLS11)
#error "NOXTLS_FEATURE_TLS11 must be 0 or 1."
#endif

#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_AES)
#error "NOXTLS_FEATURE_AES must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_AES_128)
#error "NOXTLS_FEATURE_AES_128 must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_AES_192)
#error "NOXTLS_FEATURE_AES_192 must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_AES_256)
#error "NOXTLS_FEATURE_AES_256 must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_AES_ECB)
#error "NOXTLS_FEATURE_AES_ECB must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_AES_CBC)
#error "NOXTLS_FEATURE_AES_CBC must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_AES_CTR)
#error "NOXTLS_FEATURE_AES_CTR must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_AES_CFB)
#error "NOXTLS_FEATURE_AES_CFB must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_AES_OFB)
#error "NOXTLS_FEATURE_AES_OFB must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_AES_XTS)
#error "NOXTLS_FEATURE_AES_XTS must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_AES_GCM)
#error "NOXTLS_FEATURE_AES_GCM must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_AES_CCM)
#error "NOXTLS_FEATURE_AES_CCM must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_AES_CMAC)
#error "NOXTLS_FEATURE_AES_CMAC must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_SHA224)
#error "NOXTLS_FEATURE_SHA224 must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_SHA256)
#error "NOXTLS_FEATURE_SHA256 must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_SHA384)
#error "NOXTLS_FEATURE_SHA384 must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_SHA512)
#error "NOXTLS_FEATURE_SHA512 must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_CAMELLIA)
#error "NOXTLS_FEATURE_CAMELLIA must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_ARIA)
#error "NOXTLS_FEATURE_ARIA must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_CHACHA20_POLY1305)
#error "NOXTLS_FEATURE_CHACHA20_POLY1305 must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_DES)
#error "NOXTLS_FEATURE_DES must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_RC4)
#error "NOXTLS_FEATURE_RC4 must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_RSA)
#error "NOXTLS_FEATURE_RSA must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_ECC)
#error "NOXTLS_FEATURE_ECC must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_ECDSA)
#error "NOXTLS_FEATURE_ECDSA must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_ECDH)
#error "NOXTLS_FEATURE_ECDH must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_DH)
#error "NOXTLS_FEATURE_DH must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_ML_KEM)
#error "NOXTLS_FEATURE_ML_KEM must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_ML_DSA)
#error "NOXTLS_FEATURE_ML_DSA must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_X25519)
#error "NOXTLS_FEATURE_X25519 must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_X448)
#error "NOXTLS_FEATURE_X448 must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_ED25519)
#error "NOXTLS_FEATURE_ED25519 must be 0 or 1."
#endif
#if !NOXTLS_CFG_BOOL_OK(NOXTLS_FEATURE_ED448)
#error "NOXTLS_FEATURE_ED448 must be 0 or 1."
#endif
#if NOXTLS_FEATURE_ED448 && !NOXTLS_FEATURE_SHA3
#error "NOXTLS_FEATURE_ED448 requires NOXTLS_FEATURE_SHA3 (for SHAKE256)."
#endif
#if NOXTLS_FEATURE_ED448 && !NOXTLS_FEATURE_PKC
#error "NOXTLS_FEATURE_ED448 requires NOXTLS_FEATURE_PKC."
#endif

/* Core dependency checks */
#if NOXTLS_FEATURE_DRBG && !NOXTLS_FEATURE_ENCRYPTION
#error "NOXTLS_FEATURE_DRBG requires NOXTLS_FEATURE_ENCRYPTION."
#endif

#if NOXTLS_FEATURE_DRBG && !NOXTLS_FEATURE_AES
#error "NOXTLS_FEATURE_DRBG currently requires NOXTLS_FEATURE_AES."
#endif

#if NOXTLS_FEATURE_AES && !(NOXTLS_FEATURE_AES_ECB || NOXTLS_FEATURE_AES_CBC || NOXTLS_FEATURE_AES_CTR || NOXTLS_FEATURE_AES_CFB || NOXTLS_FEATURE_AES_OFB || NOXTLS_FEATURE_AES_XTS || NOXTLS_FEATURE_AES_GCM || NOXTLS_FEATURE_AES_CCM || NOXTLS_FEATURE_AES_CMAC)
#error "NOXTLS_FEATURE_AES requires at least one NOXTLS_FEATURE_AES_* mode."
#endif

#if NOXTLS_FEATURE_AES && !(NOXTLS_FEATURE_AES_128 || NOXTLS_FEATURE_AES_192 || NOXTLS_FEATURE_AES_256)
#error "NOXTLS_FEATURE_AES requires at least one enabled key size (AES_128/AES_192/AES_256)."
#endif

#if !NOXTLS_FEATURE_AES && (NOXTLS_FEATURE_AES_128 || NOXTLS_FEATURE_AES_192 || NOXTLS_FEATURE_AES_256)
#error "NOXTLS_FEATURE_AES key-size toggles require NOXTLS_FEATURE_AES=1."
#endif

#if !NOXTLS_FEATURE_AES && (NOXTLS_FEATURE_AES_ECB || NOXTLS_FEATURE_AES_CBC || NOXTLS_FEATURE_AES_CTR || NOXTLS_FEATURE_AES_CFB || NOXTLS_FEATURE_AES_OFB || NOXTLS_FEATURE_AES_XTS || NOXTLS_FEATURE_AES_GCM || NOXTLS_FEATURE_AES_CCM || NOXTLS_FEATURE_AES_CMAC)
#error "NOXTLS_FEATURE_AES_* mode toggles require NOXTLS_FEATURE_AES=1."
#endif

#if NOXTLS_FEATURE_CERT && !NOXTLS_FEATURE_PKC
#error "NOXTLS_FEATURE_CERT requires NOXTLS_FEATURE_PKC."
#endif

#if NOXTLS_FEATURE_CERT && !NOXTLS_FEATURE_HASH
#error "NOXTLS_FEATURE_CERT requires NOXTLS_FEATURE_HASH."
#endif

#if NOXTLS_HAVE_CERT_WRITE && !NOXTLS_FEATURE_CERT
#error "NOXTLS_HAVE_CERT_WRITE requires NOXTLS_FEATURE_CERT."
#endif

#if NOXTLS_HAVE_CERT_WRITE && !NOXTLS_FEATURE_PKC
#error "NOXTLS_HAVE_CERT_WRITE requires NOXTLS_FEATURE_PKC."
#endif

#if NOXTLS_FEATURE_TLS && !NOXTLS_FEATURE_CERT
#error "NOXTLS_FEATURE_TLS requires NOXTLS_FEATURE_CERT."
#endif

#if NOXTLS_FEATURE_TLS && !NOXTLS_FEATURE_PKC
#error "NOXTLS_FEATURE_TLS requires NOXTLS_FEATURE_PKC."
#endif

#if NOXTLS_FEATURE_TLS && !NOXTLS_FEATURE_ENCRYPTION
#error "NOXTLS_FEATURE_TLS requires NOXTLS_FEATURE_ENCRYPTION."
#endif

#if NOXTLS_FEATURE_TLS && !NOXTLS_FEATURE_HASH
#error "NOXTLS_FEATURE_TLS requires NOXTLS_FEATURE_HASH."
#endif

#if NOXTLS_FEATURE_TLS && !NOXTLS_FEATURE_DRBG
#error "NOXTLS_FEATURE_TLS requires NOXTLS_FEATURE_DRBG."
#endif

#if NOXTLS_FEATURE_TLS && !NOXTLS_FEATURE_SHA256
#error "NOXTLS_FEATURE_TLS requires NOXTLS_FEATURE_SHA256."
#endif

#if NOXTLS_FEATURE_TLS && !NOXTLS_FEATURE_AES_GCM && !NOXTLS_FEATURE_CHACHA20_POLY1305
#error "NOXTLS_FEATURE_TLS requires at least one AEAD: NOXTLS_FEATURE_AES_GCM or NOXTLS_FEATURE_CHACHA20_POLY1305."
#endif

#if NOXTLS_FEATURE_TLS12 && !NOXTLS_FEATURE_TLS
#error "NOXTLS_FEATURE_TLS12 requires NOXTLS_FEATURE_TLS."
#endif

#if NOXTLS_FEATURE_TLS10 && !NOXTLS_FEATURE_TLS
#error "NOXTLS_FEATURE_TLS10 requires NOXTLS_FEATURE_TLS."
#endif

#if NOXTLS_FEATURE_TLS11 && !NOXTLS_FEATURE_TLS
#error "NOXTLS_FEATURE_TLS11 requires NOXTLS_FEATURE_TLS."
#endif

#if NOXTLS_FEATURE_TLS13 && !NOXTLS_FEATURE_TLS
#error "NOXTLS_FEATURE_TLS13 requires NOXTLS_FEATURE_TLS."
#endif

#if NOXTLS_FEATURE_DTLS && !NOXTLS_FEATURE_TLS
#error "NOXTLS_FEATURE_DTLS requires NOXTLS_FEATURE_TLS."
#endif

/* PKC intra-dependencies */
#if NOXTLS_FEATURE_ECDSA && !NOXTLS_FEATURE_ECC
#error "NOXTLS_FEATURE_ECDSA requires NOXTLS_FEATURE_ECC."
#endif

#if NOXTLS_FEATURE_ECDH && !NOXTLS_FEATURE_ECC
#error "NOXTLS_FEATURE_ECDH requires NOXTLS_FEATURE_ECC."
#endif

#if NOXTLS_FEATURE_ED25519 && !NOXTLS_FEATURE_PKC
#error "NOXTLS_FEATURE_ED25519 requires NOXTLS_FEATURE_PKC."
#endif

#if NOXTLS_FEATURE_X25519 && !NOXTLS_FEATURE_PKC
#error "NOXTLS_FEATURE_X25519 requires NOXTLS_FEATURE_PKC."
#endif

#if NOXTLS_FEATURE_X448 && !NOXTLS_FEATURE_PKC
#error "NOXTLS_FEATURE_X448 requires NOXTLS_FEATURE_PKC."
#endif

#if NOXTLS_FEATURE_ML_KEM && !NOXTLS_FEATURE_PKC
#error "NOXTLS_FEATURE_ML_KEM requires NOXTLS_FEATURE_PKC."
#endif

#if NOXTLS_FEATURE_ML_DSA && !NOXTLS_FEATURE_PKC
#error "NOXTLS_FEATURE_ML_DSA requires NOXTLS_FEATURE_PKC."
#endif

/* Profile enforcement checks. */
#if defined(NOXTLS_PROFILE_CRYPTO_ONLY) && NOXTLS_FEATURE_TLS
#error "NOXTLS_PROFILE_CRYPTO_ONLY requires NOXTLS_FEATURE_TLS=0."
#endif

#if defined(NOXTLS_PROFILE_CRYPTO_ONLY) && NOXTLS_FEATURE_CERT
#error "NOXTLS_PROFILE_CRYPTO_ONLY requires NOXTLS_FEATURE_CERT=0."
#endif

#if defined(NOXTLS_SIDECHANNEL_PROFILE_PERFORMANCE) && NOXTLS_CT_COMPARE
#error "NOXTLS_SIDECHANNEL_PROFILE_PERFORMANCE requires NOXTLS_CT_COMPARE=0."
#endif

#if defined(NOXTLS_SIDECHANNEL_PROFILE_CONSTANT_TIME_STRICT) && !NOXTLS_CT_COMPARE
#error "NOXTLS_SIDECHANNEL_PROFILE_CONSTANT_TIME_STRICT requires NOXTLS_CT_COMPARE=1."
#endif

#undef NOXTLS_CFG_BOOL_OK

#endif /* _NOXTLS_CHECK_CONFIG_H_ */
